# Generated by Django 3.0.5 on 2020-09-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHT11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='thời gian cập nhật')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nhiệt độ')),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='độ ẩm')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
